const Contact = require("../models/Contact");
const SalesOpportunity = require("../models/SalesOpportunity");
const Organization = require("../models/Organization");
const CrmActivity = require("../models/CrmActivity");
const MarketingCampaign = require("../models/MarketingCampaign");
const Event = require("../models/Event");
const SocialConnection = require("../models/SocialConnection");
const ConversationThread = require("../models/ConversationThread");
const ConversationMessage = require("../models/ConversationMessage");
const ContentBrief = require("../models/ContentBrief");
const CoachingProgram = require("../models/CoachingProgram");
const Enrollment = require("../models/Enrollment");
const CoachAssignment = require("../models/CoachAssignment");
const IntentSignal = require("../models/IntentSignal");
const growthAnalyticsService = require("./growthAnalyticsService");
const knowledgeService = require("./knowledgeService");
const salesAgentContextService = require("./salesAgentContextService");
const systemAgentHealthService = require("./systemAgentHealthService");
const searchQualityService = require("./searchQualityService");
const coachingSuccessPatternsService = require("./coachingSuccessPatternsService");

const TOOL_CLASSIFICATIONS = Object.freeze({ READ: "READ", PROPOSE: "PROPOSE", MUTATE: "MUTATE" });
const models = { Contact, SalesOpportunity, Organization, CrmActivity, MarketingCampaign, Event, SocialConnection, ConversationThread, ConversationMessage, ContentBrief, CoachingProgram, Enrollment, CoachAssignment, IntentSignal };
const limit = (value, maximum = 25) => Math.min(maximum, Math.max(1, Number(value) || 10));
const escapeRegex = (value) => String(value || "").replace(/[.*+?^${}()|[\]\\]/g, "\\$&").slice(0, 160);

const tools = [
  { id: "knowledge.retrieve", domain: "knowledge", description: "Retrieve approved workspace business knowledge.", classification: "READ", requiredCapabilities: [], allowedAgents: ["jarvis", "lead", "social", "sales", "content", "coaching", "research", "system"], handler: async ({ workspaceId, agent, input, services }) => services.knowledgeService.retrieveKnowledge({ workspaceId, query: input.query, agent, categories: input.categories, limit: input.limit }) },
  { id: "crm.get_contact", domain: "crm", description: "Read one canonical CRM contact.", classification: "READ", requiredCapabilities: ["crm.view"], allowedAgents: ["jarvis", "lead", "social", "coaching"], handler: async ({ workspaceId, input, models: db }) => db.Contact.findOne({ _id: input.contactId, workspaceId }).select("name firstName lastName email company phone title stage status sources sourceProvider socialAttribution createdAt updatedAt").lean() },
  { id: "crm.search_contacts", domain: "crm", description: "Search canonical CRM contacts by safe identity fields.", classification: "READ", requiredCapabilities: ["crm.view"], allowedAgents: ["jarvis", "lead"], handler: async ({ workspaceId, input, models: db }) => { const term = escapeRegex(input.query), filter = { workspaceId, ...(term ? { $or: [{ name: new RegExp(term, "i") }, { email: new RegExp(term, "i") }, { company: new RegExp(term, "i") }] } : {}) }; return db.Contact.find(filter).select("name email company title stage status sourceProvider updatedAt").limit(limit(input.limit)).lean(); } },
  { id: "crm.get_opportunity", domain: "sales", description: "Read one authorized sales opportunity.", classification: "READ", requiredCapabilities: ["sales.opportunities.view", "sales.opportunities.view_assigned"], capabilityMode: "any", allowedAgents: ["jarvis", "lead"], handler: async ({ workspaceId, userId, auth, input, models: db }) => db.SalesOpportunity.findOne({ _id: input.opportunityId, workspaceId, ...(!auth.effectivePermissions.includes("sales.opportunities.view") ? { ownerId: userId } : {}) }).lean() },
  { id: "crm.list_opportunities", domain: "sales", description: "List authorized sales opportunities, optionally for one contact.", classification: "READ", requiredCapabilities: ["sales.opportunities.view", "sales.opportunities.view_assigned"], capabilityMode: "any", allowedAgents: ["jarvis", "lead"], handler: async ({ workspaceId, userId, auth, input, models: db }) => db.SalesOpportunity.find({ workspaceId, ...(!auth.effectivePermissions.includes("sales.opportunities.view") ? { ownerId: userId } : {}), ...(input.stageKey ? { stageKey: input.stageKey } : {}), ...(input.contactId ? { primaryContactId: input.contactId } : {}) }).limit(limit(input.limit)).sort({ updatedAt: -1 }).lean() },
  { id: "crm.get_organization", domain: "crm", description: "Read a workspace organization.", classification: "READ", requiredCapabilities: ["crm.view"], allowedAgents: ["jarvis", "lead", "research"], handler: async ({ workspaceId, input, models: db }) => db.Organization.findOne({ _id: input.organizationId, workspaceId }).select("name domain website industry description employeeCount location linkedinUrl keywords updatedAt").lean() },
  { id: "crm.list_activity", domain: "crm", description: "List canonical CRM activity for a contact or organization.", classification: "READ", requiredCapabilities: ["crm.view"], allowedAgents: ["jarvis", "lead", "social", "coaching"], handler: async ({ workspaceId, input, models: db }) => db.CrmActivity.find({ workspaceId, ...(input.contactId ? { contactId: input.contactId } : {}), ...(input.organizationId ? { organizationId: input.organizationId } : {}) }).select("contactId organizationId type direction title body occurredAt source metadata createdBy").sort({ occurredAt: -1 }).limit(limit(input.limit)).lean() },
  { id: "sales.get_lead_context", domain: "sales", description: "Read the authorized, allowlisted Sales Agent qualification, attribution, application-status, follow-up, and activity summary.", classification: "READ", requiredCapabilities: ["sales.opportunities.view", "sales.opportunities.view_assigned"], capabilityMode: "any", allowedAgents: ["sales"], handler: async ({ workspaceId, userId, auth, input, services }) => services.salesAgentContextService.buildSalesAgentContext({ workspaceId, userId, auth, opportunityId: input.opportunityId }) },
  { id: "growth.analytics", domain: "growth", description: "Read the existing workspace growth analytics summary.", classification: "READ", requiredCapabilities: ["analytics.view"], allowedAgents: ["jarvis", "content"], handler: async ({ workspaceId, services }) => services.growthAnalyticsService.getAnalytics(workspaceId) },
  { id: "growth.list_campaigns", domain: "growth", description: "List workspace marketing campaigns.", classification: "READ", requiredCapabilities: ["campaigns.manage"], allowedAgents: ["jarvis", "content"], handler: async ({ workspaceId, input, models: db }) => db.MarketingCampaign.find({ workspaceId }).select("name type status metrics createdAt updatedAt").sort({ updatedAt: -1 }).limit(limit(input.limit)).lean() },
  { id: "growth.list_events", domain: "growth", description: "List workspace events.", classification: "READ", requiredCapabilities: ["campaigns.manage"], allowedAgents: ["jarvis", "content"], handler: async ({ workspaceId, input, models: db }) => db.Event.find({ workspaceId }).select("name summary category startDate endDate timeZone locationType location ticketPrice ticketsSold capacity status").sort({ startDate: -1 }).limit(limit(input.limit)).lean() },
  { id: "social.get_inbox_conversation", domain: "social", description: "Read one Social Inbox thread and its recent messages.", classification: "READ", requiredCapabilities: ["social.manage"], allowedAgents: ["jarvis", "social"], handler: async ({ workspaceId, input, models: db }) => { const thread = await db.ConversationThread.findOne({ _id: input.threadId, workspaceId, channel: { $in: ["facebook", "instagram", "linkedin"] } }).select("channel provider subject preview participants contactIds organizationId opportunityId assignedTo status priority unreadCount tags lastMessageAt metadata").lean(); if (!thread) return null; const messages = await db.ConversationMessage.find({ workspaceId, threadId: thread._id }).select("channel provider direction kind subject body sender recipients deliveryStatus sentAt receivedAt contactId createdBy createdAt").sort({ createdAt: -1 }).limit(limit(input.limit, 30)).lean(); return { thread, messages: messages.reverse() }; } },
  { id: "social.get_related_contact", domain: "social", description: "Read a canonical Contact only when it is linked to the selected Social Inbox thread.", classification: "READ", requiredCapabilities: ["social.manage"], allowedAgents: ["jarvis", "social"], handler: async ({ workspaceId, input, models: db }) => { const thread = await db.ConversationThread.findOne({ _id: input.threadId, workspaceId, channel: { $in: ["facebook", "instagram", "linkedin"] }, contactIds: input.contactId }).select("contactIds").lean(); return thread ? db.Contact.findOne({ _id: input.contactId, workspaceId }).select("name firstName lastName email company stage status sources sourceProvider socialAttribution createdAt updatedAt").lean() : null; } },
  { id: "social.connection_capabilities", domain: "social", description: "Read selected social-account authorization and capability status without credentials.", classification: "READ", requiredCapabilities: ["social.manage"], allowedAgents: ["jarvis", "social"], handler: async ({ workspaceId, models: db }) => db.SocialConnection.find({ workspaceId }).select("provider status scopes declinedScopes authorization expiresAt assets selectedAssetIds webhookSubscriptions connectedAt lastVerifiedAt").lean() },
  { id: "content.get_brief", domain: "content", description: "Read one workspace ContentBrief.", classification: "READ", requiredCapabilities: ["social.manage", "campaigns.manage"], capabilityMode: "any", allowedAgents: ["jarvis", "social", "content"], handler: async ({ workspaceId, input, models: db }) => db.ContentBrief.findOne({ _id: input.contentBriefId, workspaceId }).lean() },
  { id: "content.list_briefs", domain: "content", description: "List workspace content drafts and statuses.", classification: "READ", requiredCapabilities: ["social.manage", "campaigns.manage"], capabilityMode: "any", allowedAgents: ["jarvis", "social", "content"], handler: async ({ workspaceId, input, models: db }) => db.ContentBrief.find({ workspaceId, ...(input.status ? { status: input.status } : {}) }).select("title type status origin source campaignId coachingProgramId eventId social.requestedPublishAt social.publications createdAt updatedAt").sort({ updatedAt: -1 }).limit(limit(input.limit)).lean() },
  { id: "coaching.get_program", domain: "coaching", description: "Read a coaching program.", classification: "READ", requiredCapabilities: ["coaching.view", "coaching.view_assigned"], capabilityMode: "any", allowedAgents: ["jarvis", "coaching"], handler: async ({ workspaceId, input, models: db }) => db.CoachingProgram.findOne({ _id: input.programId, workspaceId }).lean() },
  { id: "coaching.get_enrollment", domain: "coaching", description: "Read an authorized coaching enrollment.", classification: "READ", requiredCapabilities: ["coaching.view", "coaching.view_assigned"], capabilityMode: "any", allowedAgents: ["jarvis", "coaching"], handler: async ({ workspaceId, userId, auth, input, models: db }) => { if (auth.effectivePermissions.includes("coaching.view")) return db.Enrollment.findOne({ _id: input.enrollmentId, workspaceId }).lean(); const assignment = await db.CoachAssignment.findOne({ workspaceId, enrollmentId: input.enrollmentId, coachUserId: userId, status: { $in: ["scheduled", "active", "completed"] } }).select("enrollmentId").lean(); return assignment ? db.Enrollment.findOne({ _id: input.enrollmentId, workspaceId }).lean() : null; } },
  { id: "coaching.get_assignment", domain: "coaching", description: "Read an authorized coaching assignment.", classification: "READ", requiredCapabilities: ["coaching.view", "coaching.view_assigned"], capabilityMode: "any", allowedAgents: ["jarvis", "coaching"], handler: async ({ workspaceId, userId, auth, input, models: db }) => db.CoachAssignment.findOne({ _id: input.assignmentId, workspaceId, ...(!auth.effectivePermissions.includes("coaching.view") ? { coachUserId: userId } : {}) }).lean() },
  { id: "system.get_pipeline_health", domain: "system", description: "Run the deterministic Lead Pipeline Health checks and return the prioritized findings for synthesis.", classification: "READ", requiredCapabilities: ["system.monitor"], allowedAgents: ["system"], handler: async ({ workspaceId, services }) => services.systemAgentHealthService.getLeadPipelineHealth(workspaceId) },
  { id: "research.list_recent_signals", domain: "research", description: "List recent Discovery intent signals (public evidence only) for synthesis into a written brief.", classification: "READ", requiredCapabilities: ["discovery.manage", "jarvis.manage"], capabilityMode: "any", allowedAgents: ["research"], handler: async ({ workspaceId, input, models: db }) => db.IntentSignal.find({ workspaceId, discoveredAt: { $gte: new Date(Date.now() - Math.min(30, Math.max(1, Number(input.days) || 7)) * 86400000) } }).select("title organizationName score classification status matchedKeywords sourceUrl discoveredAt").sort({ score: -1, discoveredAt: -1 }).limit(limit(input.limit, 100)).lean() },
  { id: "coaching.get_success_patterns", domain: "coaching", description: "Read aggregated, anonymized enrollment outcome patterns (completion rates, common drop-off stages) — never individual student data.", classification: "READ", requiredCapabilities: ["coaching.view", "coaching.view_assigned"], capabilityMode: "any", allowedAgents: ["coaching", "content"], handler: async ({ workspaceId, services }) => services.coachingSuccessPatternsService.getSuccessPatterns(workspaceId) },
  { id: "research.get_monitor_performance", domain: "research", description: "Read each Discovery monitor's real outcomes (leads, enrollments, won revenue) and deterministic quality recommendations.", classification: "READ", requiredCapabilities: ["discovery.manage", "jarvis.manage"], capabilityMode: "any", allowedAgents: ["research"], handler: async ({ workspaceId, services }) => { const performance = await services.searchQualityService.getMonitorPerformance(workspaceId); return { performance, recommendations: services.searchQualityService.recommendationsFor(performance) }; } },
];

const registry = new Map(tools.map((tool) => [tool.id, Object.freeze(tool)]));
function getTool(id) { return registry.get(String(id || "")) || null; }
function listTools() { return [...registry.values()].map(({ handler, ...metadata }) => metadata); }
module.exports = { TOOL_CLASSIFICATIONS, getTool, listTools, models, services: { growthAnalyticsService, knowledgeService, salesAgentContextService, systemAgentHealthService, searchQualityService, coachingSuccessPatternsService } };
