const definitions = [
  { id: "jarvis", displayName: "Jarvis", description: "Coordinates verified Growth Operator intelligence.", requiredCapabilities: ["jarvis.manage"], allowedTools: ["knowledge.retrieve", "crm.get_contact", "crm.search_contacts", "crm.get_opportunity", "crm.list_opportunities", "crm.get_organization", "crm.list_activity", "growth.analytics", "growth.list_campaigns", "growth.list_events", "social.get_inbox_conversation", "social.get_related_contact", "social.connection_capabilities", "content.get_brief", "content.list_briefs", "coaching.get_program", "coaching.get_enrollment", "coaching.get_assignment"], knowledgeCategories: ["dashboard/context", "campaigns", "contacts-icp", "partners-affiliates", "offers-programs", "marketing-channels", "sops", "decisions"], generateText: true, structuredOutput: true, proposeActions: true, actionsRequireApproval: true },
  { id: "lead", displayName: "Lead Agent", description: "Supports evidence-based prospect qualification and research.", requiredCapabilities: ["discovery.manage", "crm.view"], capabilityMode: "any", allowedTools: ["knowledge.retrieve", "crm.get_contact", "crm.search_contacts", "crm.get_opportunity", "crm.list_opportunities", "crm.get_organization", "crm.list_activity"], knowledgeCategories: ["contacts-icp", "offers-programs", "marketing-channels"], generateText: true, structuredOutput: true, proposeActions: true, actionsRequireApproval: true },
  { id: "social", displayName: "Social Agent", description: "Supports social inbox understanding and safe response recommendations.", requiredCapabilities: ["social.manage"], allowedTools: ["knowledge.retrieve", "crm.get_contact", "crm.list_activity", "social.get_inbox_conversation", "social.get_related_contact", "social.connection_capabilities", "content.get_brief", "content.list_briefs"], knowledgeCategories: ["offers-programs", "marketing-channels", "sops", "dashboard/context"], generateText: true, structuredOutput: true, proposeActions: true, actionsRequireApproval: true },
  { id: "sales", displayName: "Sales Agent", description: "Supports authorized opportunity prioritization and follow-up recommendations.", requiredCapabilities: ["sales.opportunities.view", "sales.opportunities.view_assigned"], capabilityMode: "any", allowedTools: ["knowledge.retrieve", "sales.get_lead_context"], knowledgeCategories: ["offers-programs", "contacts-icp", "sops", "decisions", "marketing-channels"], generateText: true, structuredOutput: true, proposeActions: true, actionsRequireApproval: true },
  { id: "content", displayName: "Content Agent", description: "Supports grounded content recommendations and drafts.", requiredCapabilities: ["social.manage", "campaigns.manage"], capabilityMode: "any", allowedTools: ["knowledge.retrieve", "content.get_brief", "content.list_briefs", "growth.list_campaigns", "growth.list_events", "growth.analytics", "coaching.get_success_patterns"], knowledgeCategories: ["offers-programs", "marketing-channels", "campaigns", "dashboard/context"], generateText: true, structuredOutput: true, proposeActions: true, actionsRequireApproval: true },
  { id: "coaching", displayName: "Coaching Agent", description: "Supports authorized coaching operations and program guidance.", requiredCapabilities: ["coaching.view", "coaching.view_assigned"], capabilityMode: "any", allowedTools: ["knowledge.retrieve", "crm.get_contact", "crm.list_activity", "coaching.get_program", "coaching.get_enrollment", "coaching.get_assignment", "coaching.get_success_patterns"], knowledgeCategories: ["offers-programs", "sops", "decisions"], generateText: true, structuredOutput: true, proposeActions: true, actionsRequireApproval: true },
  { id: "research", displayName: "Research Agent", description: "Synthesizes supplied research evidence conservatively.", requiredCapabilities: ["discovery.manage", "jarvis.manage"], capabilityMode: "any", allowedTools: ["knowledge.retrieve", "crm.search_contacts", "crm.get_organization", "research.list_recent_signals", "research.get_monitor_performance"], knowledgeCategories: ["contacts-icp", "marketing-channels", "partners-affiliates"], generateText: true, structuredOutput: true, proposeActions: false, actionsRequireApproval: true },
  { id: "system", displayName: "System Agent", description: "Monitors pipeline and system health across every other agent, without duplicating their work. Never contacts anyone, publishes, deletes, or changes data — only reports and recommends.", requiredCapabilities: ["system.monitor"], allowedTools: ["knowledge.retrieve", "system.get_pipeline_health"], knowledgeCategories: ["dashboard/context", "sops", "decisions"], generateText: true, structuredOutput: true, proposeActions: false, actionsRequireApproval: true },
];

const registry = new Map(definitions.map((definition) => [definition.id, Object.freeze({ ...definition, workspaceConfigKey: definition.id, enabledByWorkspaceConfig: true, allowedTools: Object.freeze(definition.allowedTools), knowledgeCategories: Object.freeze(definition.knowledgeCategories) })]));
function getAgent(id) { return registry.get(String(id || "")) || null; }
function listAgents() { return [...registry.values()]; }
module.exports = { getAgent, listAgents };
