const templates = Object.freeze([
  { key: "ambassador_welcome", name: "Ambassador profile → welcome draft", description: "After profile completion, notify the team and generate a review-only welcome draft when workspace permission is enabled. Never publishes automatically.", trigger: { eventType: "ambassador.profile.completed" }, conditions: [], actions: [{ type: "notification.create", config: { title: "Ambassador profile ready for review" } }, { type: "ambassador.welcome_draft", config: {} }] },
  { key: "ambassador_profile_reminder", name: "Ambassador profile reminder", description: "After account activation, wait three days and notify an ambassador in-app only if their profile remains incomplete.", trigger: { eventType: "team.invitation.accepted" }, conditions: [{ field: "event.roles", operator: "contains", value: "ambassador" }], actions: [{ type: "ambassador.profile_reminder", delayMinutes: 4320, config: { title: "Complete your ambassador profile", body: "Add your headshot and required profile information so your welcome post can be prepared." } }] },
  { key: "ambassador_task_followup", name: "Ambassador content assignment follow-up", description: "Create an internal follow-up task after an ambassador content assignment.", trigger: { eventType: "ambassador.content.assigned" }, conditions: [], actions: [{ type: "task.create", config: { title: "Review ambassador content task", dueMinutes: 4320 } }] },
  { key: "application_completed", name: "Application completed", description: "Confirm the application, notify the closer, and create follow-up.", trigger: { eventType: "application.completed" }, conditions: [], actions: [{ type: "contact.add_tag", config: { tag: "application-completed" } }, { type: "communication.email", config: { purpose: "transactional", subject: "We received your application", body: "Hi {{contact.firstName}}, we received your application and will be in touch." } }, { type: "communication.sms", config: { purpose: "transactional", body: "We received your Ellie Coaching application. We will be in touch soon." } }, { type: "notification.create", config: { role: "closer", title: "New coaching application" } }, { type: "task.create", config: { title: "Follow up on coaching application", dueMinutes: 1440 } }] },
  { key: "call_booked", name: "Call booked", description: "Send confirmations, notify the team immediately, and create configurable reminder jobs.", trigger: { eventType: "coaching.session.scheduled" }, conditions: [], actions: [{ type: "communication.email", config: { purpose: "transactional", subject: "Your call is booked", body: "Your call is confirmed. Check your calendar for the meeting details." } }, { type: "communication.sms", config: { purpose: "transactional", body: "Your call is booked. Check your calendar for details." } }, { type: "notification.create", config: { role: "closer", title: "New call booked" } }, { type: "communication.session_reminders", config: { offsetsMinutes: [1440, 120], channels: ["email", "sms"] } }] },
  { key: "closed_won", name: "Closed won onboarding", description: "Create enrollment, commission, access, and welcome steps after a sale.", trigger: { eventType: "opportunity.closed_won" }, conditions: [], actions: [{ type: "enrollment.create", config: { coachingProgramId: "", status: "active" } }, { type: "commission.generate", config: {} }, { type: "skool.request_access", config: {} }, { type: "communication.onboarding", config: { channels: ["email", "sms"] } }] },
  { key: "coach_assignment", name: "Coach assignment notification", description: "Notify the assigned coach when a student becomes visible in Coach Portal.", trigger: { eventType: "coach.assigned" }, conditions: [], actions: [{ type: "notification.create", config: { role: "coach", title: "New student assignment" } }] },
  { key: "coach_handoff", name: "Coach handoff notification", description: "Notify the incoming coach after preserved handoff completion.", trigger: { eventType: "coaching.handoff.completed" }, conditions: [], actions: [{ type: "notification.create", config: { role: "coach", title: "Student handoff completed" } }] },
  { key: "social_lead", name: "Social lead follow-up", description: "Tag a social lead, create a tracked application CTA, and follow up only if still needed.", trigger: { eventType: "social.lead.created" }, conditions: [], actions: [{ type: "contact.add_tag", config: { tag: "social-lead" } }, { type: "social.tracked_link", config: { destination: "https://elliescoaching.com/apply" } }, { type: "task.create", delayMinutes: 1440, conditions: [{ field: "contact.applicationCompleted", operator: "equals", value: false }], config: { title: "Review social lead application status" } }] },
  { key: "eventbrite_lead", name: "Eventbrite registration nurture", description: "Tag registrants and schedule consent-aware event follow-up.", trigger: { eventType: "event.registered" }, conditions: [], actions: [{ type: "contact.add_tag", config: { tag: "eventbrite-registrant" } }, { type: "communication.email", config: { purpose: "transactional", subject: "Registration confirmed", body: "Your registration is confirmed. We look forward to seeing you." } }] },
  { key: "session_reminders", name: "Coaching session reminders", description: "Create editable 24-hour and 2-hour reminders using the existing stale-job safeguards.", trigger: { eventType: "coaching.session.scheduled" }, conditions: [], actions: [{ type: "communication.session_reminders", config: { offsetsMinutes: [1440, 120], channels: ["email"] } }] },
  { key: "payment_reminder_upcoming", name: "Upcoming installment reminder", description: "Email a client a few days before a scheduled payment installment is due.", trigger: { eventType: "payment.installment.upcoming" }, conditions: [], actions: [{ type: "communication.email", config: { purpose: "transactional", subject: "Upcoming payment reminder", body: "Hi {{contact.firstName}}, this is a reminder that your next payment installment is coming due soon. If you have any questions about your payment plan, just reply to this email." } }] },
  { key: "payment_reminder_past_due", name: "Past-due installment alert", description: "Email a client and notify the team when a payment installment goes past due.", trigger: { eventType: "payment.installment.past_due" }, conditions: [], actions: [{ type: "communication.email", config: { purpose: "transactional", subject: "Payment past due", body: "Hi {{contact.firstName}}, one of your program payments has passed its due date and hasn't gone through yet. Please update your payment method to keep your enrollment on track. Reply to this email if you need help." } }, { type: "notification.create", config: { role: "closer", title: "Client payment past due" } }] },
  { key: "payment_declined", name: "Payment declined alert", description: "Instantly email a client and notify the team when a card is declined at checkout, separate from the past-due poller.", trigger: { eventType: "payment.transaction.failed" }, conditions: [], actions: [{ type: "communication.email", config: { purpose: "transactional", subject: "Your payment didn't go through", body: "Hi {{contact.firstName}}, we tried to run your card and it was declined. Please update your payment method so we can keep things moving — reply to this email if you'd like help." } }, { type: "notification.create", config: { role: "closer", title: "Client card declined" } }] },
  // Placeholder copy below is intentionally marked [PLACEHOLDER] in the
  // subject line so it's unmistakable in the Automations dashboard which
  // sequences still need Ellie's real voice — edit the subject/body on each
  // action the same way as every other automation (Edit -> Advanced action
  // settings). purpose:"marketing" on all of these so they respect a
  // contact's unsubscribe/consent status and carry an unsubscribe link,
  // unlike the transactional ones above.
  { key: "closed_lost_nurture", name: "Closed-lost re-engagement", description: "Tag a lost deal and send one immediate note, then a longer-term re-engagement email a month later.", trigger: { eventType: "opportunity.closed_lost" }, conditions: [], actions: [{ type: "contact.add_tag", config: { tag: "closed-lost" } }, { type: "communication.email", config: { purpose: "marketing", subject: "[PLACEHOLDER] Not the right time — we're here when it is", body: "[PLACEHOLDER COPY — replace with Ellie's voice] Hi {{contact.firstName}}, totally understand now isn't the right time. If anything changes, we'd love to pick the conversation back up." } }, { type: "communication.email", delayMinutes: 43200, config: { purpose: "marketing", subject: "[PLACEHOLDER] Checking back in", body: "[PLACEHOLDER COPY — replace with Ellie's voice] Hi {{contact.firstName}}, it's been a little while — wanted to check in and see if now's a better time to talk about your goals." } }] },
  { key: "program_completed_sequence", name: "Graduation, testimonial, referral & upsell sequence", description: "Congratulate a graduate immediately, then ask for a testimonial, a referral, and offer a next step over the following weeks.", trigger: { eventType: "coaching.program.completed" }, conditions: [], actions: [
    { type: "communication.email", config: { purpose: "marketing", subject: "[PLACEHOLDER] Congratulations on finishing the program!", body: "[PLACEHOLDER COPY — replace with Ellie's voice] Hi {{contact.firstName}}, congratulations on completing the program! We're proud of the work you put in." } },
    { type: "communication.email", delayMinutes: 4320, config: { purpose: "marketing", subject: "[PLACEHOLDER] Would you share your experience?", body: "[PLACEHOLDER COPY — replace with Ellie's voice] Hi {{contact.firstName}}, now that you've had a few days to settle back in, would you be willing to share a quick testimonial about your experience?" } },
    { type: "communication.email", delayMinutes: 20160, config: { purpose: "marketing", subject: "[PLACEHOLDER] Know someone who'd love this program?", body: "[PLACEHOLDER COPY — replace with Ellie's voice] Hi {{contact.firstName}}, if you know someone who could use the same support you just got, we'd love an introduction." } },
    { type: "communication.email", delayMinutes: 43200, config: { purpose: "marketing", subject: "[PLACEHOLDER] Your next step", body: "[PLACEHOLDER COPY — replace with Ellie's voice] Hi {{contact.firstName}}, now that you've completed the program, here's a next step to keep building on what you learned." } },
  ] },
]);
module.exports = { templates };
