const Contact = require("../models/Contact"); const SalesOpportunity = require("../models/SalesOpportunity"); const Enrollment = require("../models/Enrollment"); const CoachAssignment = require("../models/CoachAssignment"); const CoachingSession = require("../models/CoachingSession"); const CoachingHandoff = require("../models/CoachingHandoff"); const CoachingProgram = require("../models/CoachingProgram"); const CoachProfile = require("../models/CoachProfile"); const ReferralAttribution = require("../models/ReferralAttribution"); const CommissionLedger = require("../models/CommissionLedger"); const SkoolPurchase = require("../models/SkoolPurchase"); const ConversationMessage = require("../models/ConversationMessage"); const MessageDeliveryEvent = require("../models/MessageDeliveryEvent"); const CommunicationJob = require("../models/CommunicationJob"); const MarketingCampaign = require("../models/MarketingCampaign");
const deps={Contact,SalesOpportunity,Enrollment,CoachAssignment,CoachingSession,CoachingHandoff,CoachingProgram,CoachProfile,ReferralAttribution,CommissionLedger,SkoolPurchase,ConversationMessage,MessageDeliveryEvent,CommunicationJob,MarketingCampaign};
const money=(value)=>Math.round((Number(value)||0)*100)/100; const rate=(a,b)=>b?Math.round(a/b*1000)/10:0;
function sourceFor(contact){return contact?.socialAttribution?.first?.provider||contact?.sourceProvider||contact?.sources?.[0]||"organic/direct";}
function group(rows,keyFn,valueFn=()=>1){const map=new Map();for(const row of rows){const key=keyFn(row)||"unknown";map.set(String(key),(map.get(String(key))||0)+valueFn(row));}return[...map].map(([key,value])=>({key,value})).sort((a,b)=>b.value-a.value);}
async function getAnalytics(workspaceId,models=deps){
 const scope=workspaceId?{workspaceId}:{};
 const [contacts,opportunities,enrollments,assignments,sessions,handoffs,programs,coaches,referrals,commissions,purchases,messages,deliveryEvents,jobs,campaigns]=await Promise.all([
  models.Contact.find(scope).lean(),models.SalesOpportunity.find(scope).lean(),models.Enrollment.find(scope).lean(),models.CoachAssignment.find(scope).lean(),models.CoachingSession.find(scope).lean(),models.CoachingHandoff.find(scope).lean(),models.CoachingProgram.find(scope).lean(),models.CoachProfile.find(scope).lean(),models.ReferralAttribution.find(scope).lean(),models.CommissionLedger.find(scope).lean(),models.SkoolPurchase.find(scope).lean(),models.ConversationMessage.find(scope).lean(),models.MessageDeliveryEvent.find(scope).lean(),models.CommunicationJob.find(scope).lean(),models.MarketingCampaign.find(scope).lean(),
 ]);
 const contactMap=new Map(contacts.map(c=>[String(c._id),c])); const programMap=new Map(programs.map(p=>[String(p._id),p])); const coachMap=new Map(coaches.map(c=>[String(c._id),c])); const campaignMap=new Map(campaigns.map(c=>[String(c._id),c]));
 const won=opportunities.filter(o=>o.wonAt||o.stageKey==="won"),lost=opportunities.filter(o=>o.lostAt||o.stageKey==="lost"); const applications=contacts.filter(c=>c.additionalFields?.applicationCompletedAt||c.tags?.includes("application-completed")); const qualified=contacts.filter(c=>c.qualifyContact||["qualified","proposal"].includes(c.stage)); const booked=sessions.filter(s=>s.status!=="cancelled"); const attended=sessions.filter(s=>s.zoom?.attendance?.state==="attended");
 const funnel=[{key:"leads",value:contacts.length},{key:"applications",value:applications.length},{key:"qualified",value:qualified.length},{key:"calls_booked",value:booked.length},{key:"calls_attended",value:attended.length},{key:"closed_won",value:won.length},{key:"closed_lost",value:lost.length},{key:"enrollments",value:enrollments.length},{key:"active_students",value:enrollments.filter(e=>e.status==="active").length},{key:"alumni",value:enrollments.filter(e=>e.status==="completed").length}];
 const conversions=funnel.slice(1).map((item,index)=>({from:funnel[index].key,to:item.key,rate:rate(item.value,funnel[index].value)})); const closedWonRevenue=won.reduce((s,o)=>s+Number(o.value||0),0); const coachingOpportunityIds=new Set(enrollments.map(e=>String(e.sourceOpportunityId||"")).filter(Boolean)); const programRevenue=won.filter(o=>coachingOpportunityIds.has(String(o._id))).reduce((s,o)=>s+Number(o.value||0),0); const addonRevenue=purchases.reduce((s,p)=>s+Number(p.amountMinor||0)/100,0); const referralContactIds=new Set(referrals.map(r=>String(r.contactId))); const referralRevenue=won.filter(o=>referralContactIds.has(String(o.primaryContactId))).reduce((s,o)=>s+Number(o.value||0),0); const commissionExpense=commissions.filter(c=>c.status!=="reversed").reduce((s,c)=>s+Number(c.commissionAmountMinor||0)/100,0); const uniqueCustomers=new Set(won.map(o=>String(o.primaryContactId)).filter(Boolean)).size;
 const sourceRows=contacts.map(c=>({source:sourceFor(c),contact:c})); const attribution=group(sourceRows,r=>r.source).map(row=>{const ids=new Set(sourceRows.filter(r=>r.source===row.key).map(r=>String(r.contact._id)));const sourceWon=won.filter(o=>ids.has(String(o.primaryContactId)));return{source:row.key,leads:row.value,percentOfLeads:rate(row.value,contacts.length),applications:applications.filter(c=>ids.has(String(c._id))).length,sales:sourceWon.length,revenue:money(sourceWon.reduce((s,o)=>s+Number(o.value||0),0)),conversionRate:rate(sourceWon.length,row.value)};});
 const byCampaign=group(won,o=>campaignMap.get(String(o.campaignId))?.name||contactMap.get(String(o.primaryContactId))?.socialAttribution?.first?.contentId||"unattributed",o=>Number(o.value||0)).map(r=>({campaign:r.key,revenue:money(r.value),sales:won.filter(o=>(campaignMap.get(String(o.campaignId))?.name||contactMap.get(String(o.primaryContactId))?.socialAttribution?.first?.contentId||"unattributed")===r.key).length}));
 const contentRows=contacts.filter(c=>c.socialAttribution?.first?.contentId).map(c=>({contentId:c.socialAttribution.first.contentId,provider:c.socialAttribution.first.provider||"",contact:c})); const byContent=group(contentRows,r=>r.contentId).map(row=>{const ids=new Set(contentRows.filter(r=>r.contentId===row.key).map(r=>String(r.contact._id)));const contentWon=won.filter(o=>ids.has(String(o.primaryContactId)));return{contentId:row.key,provider:contentRows.find(r=>r.contentId===row.key)?.provider||"",leads:row.value,percentOfLeads:rate(row.value,contacts.length),applications:applications.filter(c=>ids.has(String(c._id))).length,sales:contentWon.length,revenue:money(contentWon.reduce((s,o)=>s+Number(o.value||0),0)),conversionRate:rate(contentWon.length,row.value)};});
 const byReferral=group(won.filter(o=>referralContactIds.has(String(o.primaryContactId))),o=>{const ref=referrals.find(r=>String(r.contactId)===String(o.primaryContactId));return coachMap.get(String(ref?.coachProfileId))?.displayName||ref?.referralCode||"unknown";},o=>Number(o.value||0)).map(r=>({coach:r.key,revenue:money(r.value)}));
 const communication={email:{sent:messages.filter(m=>m.channel==="email"&&m.direction==="outbound").length,delivered:deliveryEvents.filter(e=>e.provider==="resend"&&e.status==="delivered").length,opened:deliveryEvents.filter(e=>e.provider==="resend"&&["opened","email.opened"].includes(e.status)).length,clicked:deliveryEvents.filter(e=>e.provider==="resend"&&["clicked","email.clicked"].includes(e.status)).length,bounced:deliveryEvents.filter(e=>e.provider==="resend"&&e.status.includes("bounce")).length},sms:{sent:messages.filter(m=>m.channel==="sms"&&m.direction==="outbound").length,delivered:deliveryEvents.filter(e=>e.provider==="twilio"&&e.status==="delivered").length,replies:messages.filter(m=>m.channel==="sms"&&m.direction==="inbound").length},blocked:jobs.filter(j=>j.status==="blocked").length,reminders:{sent:jobs.filter(j=>j.kind==="session_reminder"&&j.status==="sent").length,blocked:jobs.filter(j=>j.kind==="session_reminder"&&j.status==="blocked").length},campaigns:campaigns.map(c=>({id:c._id,name:c.name,status:c.status,...(c.metrics||{})}))};
 const noShowSessions=sessions.filter(s=>s.zoom?.attendance?.state==="no_show"); const coaching={activeStudents:enrollments.filter(e=>e.status==="active").length,studentsPerCoach:group(assignments.filter(a=>["active","scheduled"].includes(a.status)),a=>coachMap.get(String(a.coachProfileId))?.displayName||"unknown"),upcomingAssignments:assignments.filter(a=>a.status==="scheduled").length,completedAssignments:assignments.filter(a=>a.status==="completed").length,handoffs:handoffs.length,attendance:{attended:attended.length,noShows:noShowSessions.length,unknown:sessions.filter(s=>s.zoom?.attendance?.state==="unknown").length},noShowStudents:noShowSessions.slice(0,25).map(s=>({contactId:s.contactId,name:contactMap.get(String(s.contactId))?.name||"Unknown student",startsAt:s.startsAt})),programEnrollments:group(enrollments,e=>programMap.get(String(e.coachingProgramId))?.name||e.programSnapshot?.name||"unknown"),programCompletions:group(enrollments.filter(e=>e.status==="completed"),e=>programMap.get(String(e.coachingProgramId))?.name||e.programSnapshot?.name||"unknown")};
 communication.failures=jobs.filter(j=>["failed","blocked"].includes(j.status)).slice(0,25).map(j=>({id:j._id,status:j.status,channel:j.channel,reason:j.blockReason||"",contactId:j.contactId}));
 return{generatedAt:new Date(),funnel:{stages:funnel,conversions},attribution:{bySource:attribution,byCampaign,byContent,byCoachReferral:byReferral,social:attribution.filter(r=>["instagram","facebook","tiktok","linkedin","x"].includes(r.source))},revenue:{closedWon:money(closedWonRevenue),programRevenue:money(programRevenue),addonRevenue:money(addonRevenue),referralGenerated:money(referralRevenue),commissionExpense:money(commissionExpense),customerLifetimeValue:uniqueCustomers?money((closedWonRevenue+addonRevenue)/uniqueCustomers):0,total:money(closedWonRevenue+addonRevenue)},coaching,referrals:{total:referrals.length,pendingCommission:money(commissions.filter(c=>c.status==="pending").reduce((s,c)=>s+Number(c.commissionAmountMinor||0)/100,0)),paidCommission:money(commissions.filter(c=>c.status==="paid").reduce((s,c)=>s+Number(c.commissionAmountMinor||0)/100,0)),byCoach:byReferral},communication};
}
module.exports={getAnalytics,group,sourceFor,_deps:deps};
