const express = require('express');
const { requireCapability, requireRole } = require('../middleware/auth');
const service = require('../services/searchReportingService');
const imports = require('../services/aiVisibilityImport');
const router = express.Router();
router.use(requireCapability('analytics.view'));
router.use((req,res,next)=>{res.set('Cache-Control','no-store');next();});
const admin = requireRole('owner','admin');
const run = fn => async(req,res)=>{try{res.json({success:true,data:await fn(req)});}catch(error){res.status(error.status || 502).json({error:error.status ? error.message : 'Reporting operation failed. Please retry or check the connection setup.'});}};
router.get('/status',run(req=>service.status(req.auth.workspaceId)));
router.get('/reports',run(req=>service.reports(req.auth.workspaceId,req.query.days)));
router.post('/google/start',admin,run(req=>service.start(req.auth.workspaceId,req.auth.user._id)));
router.get('/google/properties',admin,run(req=>service.properties(req.auth.workspaceId)));
router.put('/google/properties',admin,run(req=>service.selectGoogle(req.auth.workspaceId,req.body || {})));
router.post('/bing/connect',admin,run(req=>service.connectBing(req.auth.workspaceId,req.body || {})));
router.post('/bing/sitemap',admin,run(req=>service.submitSitemap(req.auth.workspaceId)));
router.delete('/connection/:provider',admin,run(req=>service.disconnect(req.auth.workspaceId,req.params.provider)));
router.get('/visibility',run(req=>imports.list(req.auth.workspaceId)));
router.post('/visibility',admin,run(req=>imports.save(req.auth.workspaceId,req.auth.user._id,req.body || {})));
router.delete('/visibility/:provider',admin,run(req=>imports.remove(req.auth.workspaceId,req.params.provider)));
module.exports=router;
