import { useEffect, useState } from "react";
import { FiAlertCircle, FiCheck, FiCreditCard, FiExternalLink, FiRefreshCw, FiShield } from "react-icons/fi";
import { createApplicationPaymentRequest, disconnectSquareConnection, fetchManagedApplications, fetchPaymentConnection, fetchPaymentTransactions, refundPaymentTransaction, refreshSquareConnection, startSquareOAuth } from "../services/api.js";
import { hasPermission } from "../utils/roleAccess.js";
import useAuth from "../context/useAuth.js";
import "./PaymentSettings.css";
import PaymentPlanPanel from "./PaymentPlanPanel.jsx";
import useModalLayer from "../hooks/useModalLayer.js";

const money = (amount, currency = "USD") => new Intl.NumberFormat(undefined, { style: "currency", currency }).format((amount || 0) / 100);
const message = (error, fallback) => error?.response?.data?.error || fallback;

export default function PaymentSettings() {
  const { session } = useAuth();
  const canManage = hasPermission(session, "payments.manage");
  const [connection, setConnection] = useState(null);
  const [transactions, setTransactions] = useState([]), [applications, setApplications] = useState([]), [paymentLink, setPaymentLink] = useState("");
  const [form, setForm] = useState({ applicationId: "", kind: "full", amount: "" });
  const [notice, setNotice] = useState(null), [busy, setBusy] = useState(false), [refund, setRefund] = useState(null), [confirmDisconnect, setConfirmDisconnect] = useState(false);
  useModalLayer(Boolean(confirmDisconnect || refund));
  const fetchData = async () => { const [status, activity] = await Promise.all([fetchPaymentConnection(), fetchPaymentTransactions()]); const applicationItems = canManage ? await fetchManagedApplications() : []; return { status, activity, applicationItems }; };
  const applyData = ({ status, activity, applicationItems }) => { setConnection(status.connection); setTransactions(activity); setApplications(applicationItems.filter((item) => ["submitted", "reviewing", "qualified"].includes(item.status) && item.coachingProgramId)); };
  const load = async () => applyData(await fetchData());
  useEffect(() => { let active = true; fetchData().then((data) => { if (active) applyData(data); }).catch((error) => { if (active) setNotice({ type: "error", text: message(error, "Payments could not be loaded.") }); }); return () => { active = false; }; }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const act = async (operation, success) => { setBusy(true); setNotice(null); try { await operation(); await load(); setNotice({ type: "success", text: success }); return true; } catch (error) { setNotice({ type: "error", text: message(error, "The payment action could not be completed.") }); return false; } finally { setBusy(false); } };
  const connect = async () => { setBusy(true); try { const data = await startSquareOAuth(); window.location.assign(data.authorizationUrl); } catch (error) { setNotice({ type: "error", text: message(error, "Square connection could not be started.") }); setBusy(false); } };
  const create = (event) => { event.preventDefault(); act(async () => { const result = await createApplicationPaymentRequest(form.applicationId, { kind: form.kind, amountMinor: form.kind === "deposit" ? Math.round(Number(form.amount) * 100) : undefined }); setPaymentLink(result.publicPaymentUrl); setForm({ applicationId: "", kind: "full", amount: "" }); }, "Application accepted and secure payment request created."); };
  return <div className="payment-settings">
    <header><div><p className="page-eyebrow">Payments</p><h2>Square payments</h2><p>Connect a seller account, create secure hosted payment links, and track verified payments.</p></div><span className={`payment-status payment-status--${connection?.status || "disconnected"}`}>{connection?.status === "connected" ? <FiCheck /> : <FiAlertCircle />}{connection?.status === "connected" ? "Connected" : connection?.status === "attention_required" ? "Needs attention" : "Not connected"}</span></header>
    {notice ? <p className={`payment-notice payment-notice--${notice.type}`} role="status">{notice.text}</p> : null}
    <section className="payment-connection-card"><div className="payment-provider"><span><FiCreditCard /></span><div><h3>Square</h3><p>{connection ? `${connection.merchantName || "Square seller"}${connection.locationName ? ` · ${connection.locationName}` : ""}` : "Connect with Square OAuth. Lead Porch never receives your Square password or customer card details."}</p></div></div><div className="payment-actions">{!connection || ["disconnected", "expired", "attention_required"].includes(connection.status) ? <button className="btn btn-primary" disabled={!canManage || busy} onClick={connect}>{connection ? "Reconnect Square" : "Connect Square"}</button> : <><button className="btn btn-secondary" disabled={busy} onClick={() => act(() => refreshSquareConnection(), "Square authorization refreshed and verified.")}><FiRefreshCw /> Refresh authorization</button>{canManage ? <button className="btn btn-danger" disabled={busy} onClick={() => setConfirmDisconnect(true)}>Disconnect</button> : null}</>}</div><details><summary>Connection details</summary><dl><div><dt>Authorization</dt><dd>Encrypted OAuth</dd></div><div><dt>Connected</dt><dd>{connection?.connectedAt ? new Date(connection.connectedAt).toLocaleString() : "Not connected"}</dd></div><div><dt>Last verified</dt><dd>{connection?.lastVerifiedAt ? new Date(connection.lastVerifiedAt).toLocaleString() : "Not yet"}</dd></div><div><dt>Authorization expires</dt><dd>{connection?.tokenExpiresAt ? new Date(connection.tokenExpiresAt).toLocaleDateString() : "Provided by Square"}</dd></div></dl></details></section>
    <div className="payment-grid">
      {canManage ? <form className="payment-panel" onSubmit={create}><div className="payment-panel__heading"><div><h3>Accept application & request payment</h3><p>Select the applicant. Lead Porch uses the published program and server-side price.</p></div><FiShield /></div><label>Applicant<select required value={form.applicationId} onChange={(e) => setForm({ ...form, applicationId: e.target.value })}><option value="">Select a pending application</option>{applications.map((item) => <option key={item._id} value={item._id}>{item.contactId?.name || item.contactId?.email} · {item.coachingProgramId?.name}</option>)}</select></label><div className="payment-form-row"><label>Payment type<select value={form.kind} onChange={(e) => setForm({ ...form, kind: e.target.value, amount: "" })}><option value="full">Full published price</option><option value="deposit">Authorized deposit</option></select></label>{form.kind === "deposit" ? <label>Deposit amount (USD)<input required min="0.01" step="0.01" inputMode="decimal" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} /></label> : null}</div><button className="btn btn-primary" disabled={busy || connection?.status !== "connected"}>Accept & create payment request <FiExternalLink /></button>{paymentLink ? <div className="payment-request-link"><label>Applicant payment link<input readOnly value={paymentLink} /></label><button type="button" className="btn btn-secondary" onClick={() => navigator.clipboard.writeText(paymentLink)}>Copy link</button></div> : null}</form> : null}
      <section className="payment-panel"><div className="payment-panel__heading"><div><h3>Enrollment safety</h3><p>A verified Square webhook is the only event that can mark a payment paid.</p></div><FiShield /></div><p className="payment-enrollment-note">A pending enrollment is created automatically the moment a payment is verified — no coach is assigned automatically, and this always happens; it isn&rsquo;t a setting to turn on or off.</p></section>
    </div>
    <PaymentPlanPanel canManage={canManage} connectionStatus={connection?.status} busy={busy} runAction={act} /><section className="payment-panel payment-activity"><div className="payment-panel__heading"><div><h3>Payment activity</h3><p>Workspace-scoped payment links, verified payments, and refunds.</p></div></div>{transactions.length ? <div className="payment-table-wrap"><table><thead><tr><th>Customer</th><th>Program</th><th>Amount</th><th>Status</th><th>Date</th><th>Action</th></tr></thead><tbody>{transactions.map((item) => <tr key={item._id}><td>{item.contactId?.name || item.description || "Payment"}</td><td>{item.coachingProgramId?.name || "—"}</td><td>{money(item.amountMinor, item.currency)}</td><td><span className={`payment-status payment-status--${item.status}`}>{item.status.replaceAll("_", " ")}</span></td><td>{new Date(item.createdAt).toLocaleDateString()}</td><td>{item.checkoutUrl && item.status === "pending" ? <a href={item.checkoutUrl} target="_blank" rel="noreferrer">Open link</a> : null}{canManage && ["paid", "partially_refunded"].includes(item.status) ? <button className="payment-link-button" onClick={() => setRefund(item)}>Refund</button> : null}</td></tr>)}</tbody></table></div> : <div className="payment-empty"><FiCreditCard /><h4>No payment activity yet</h4><p>Created links and verified Square payments will appear here.</p></div>}</section>
    {confirmDisconnect ? <div className="payment-modal" role="dialog" aria-modal="true" aria-labelledby="disconnect-title" onKeyDown={(event) => { if (event.key === "Escape" && !busy) setConfirmDisconnect(false); }}><div><h3 id="disconnect-title">Disconnect Square?</h3><p>Lead Porch will revoke this workspace’s Square authorization. Existing payment and audit history will be preserved.</p><div><button autoFocus type="button" className="btn btn-secondary" onClick={() => setConfirmDisconnect(false)}>Keep connected</button><button type="button" className="btn btn-danger" disabled={busy} onClick={() => { setConfirmDisconnect(false); act(() => disconnectSquareConnection(), "Square disconnected. Payment history was preserved."); }}>Disconnect Square</button></div></div></div> : null}
    {refund ? <div className="payment-modal" role="dialog" aria-modal="true" aria-labelledby="refund-title" onKeyDown={(event) => { if (event.key === "Escape" && !busy) setRefund(null); }}><form onSubmit={async (e) => { e.preventDefault(); const data = new FormData(e.currentTarget); const completed = await act(() => refundPaymentTransaction(refund._id, { amountMinor: Math.round(Number(data.get("amount")) * 100), reason: data.get("reason") }), "Refund submitted to Square."); if (completed) setRefund(null); }}><h3 id="refund-title">Refund payment</h3><p>Available balance: {money(refund.amountMinor - (refund.refunds || []).filter((item) => ["pending", "completed"].includes(item.status)).reduce((sum, item) => sum + item.amountMinor, 0), refund.currency)}</p><label>Refund amount<input autoFocus name="amount" type="number" min="0.01" max={(refund.amountMinor - (refund.refunds || []).filter((item) => ["pending", "completed"].includes(item.status)).reduce((sum, item) => sum + item.amountMinor, 0)) / 100} step="0.01" required /></label><label>Reason<textarea name="reason" required maxLength="500" /></label><div><button type="button" className="btn btn-secondary" disabled={busy} onClick={() => setRefund(null)}>Cancel</button><button className="btn btn-danger" disabled={busy}>{busy ? "Submitting…" : "Submit refund"}</button></div></form></div> : null}
  </div>;
}
