import { useEffect, useState } from 'react';
import api from '../services/api.js';
import useAuth from '../context/useAuth.js';
import './SearchVisibilityPanel.css';
const base = '/analytics/search';
const number = value => Number(value || 0).toLocaleString();
const get = path => api.get(base + path).then(r => r.data.data);
function SearchCard({ title, report }) {
  const [tab,setTab]=useState('queries');
  return <article className="search-report"><h3>{title}</h3>
    {!report || !['ready','stale'].includes(report.state) ? <p>{report?.message || 'Loading report…'}</p> : <>
      {report.state==='stale' && <p role="status" className="search-warning">Refresh failed. Showing saved data. {report.error}</p>}
      <small>{report.property} · Retrieved {new Date(report.fetchedAt).toLocaleString()}</small>
      <dl className="search-totals"><div><dt>Impressions</dt><dd>{number(report.totals.impressions)}</dd></div><div><dt>Clicks</dt><dd>{number(report.totals.clicks)}</dd></div><div><dt>Click-through rate</dt><dd>{(report.totals.ctr*100).toFixed(2)}%</dd></div></dl>
      <p>{report.note}</p><p>Provider returned {report.daily.length} daily records for this period.</p>
      <div className="search-tabs">{['queries',...(report.pages?['pages','countries','devices']:[]),'daily'].map(t=><button type="button" key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t==='queries'?'Search queries':t==='pages'?'Pages':t==='countries'?'Countries':t==='devices'?'Devices':'Daily totals'}</button>)}</div>
      <div className="search-table"><table><caption>{title}: {tab}</caption><thead><tr><th>{tab==='daily'?'Date':tab==='pages'?'Page':tab==='countries'?'Country':tab==='devices'?'Device':'Query'}</th><th>Impressions</th><th>Clicks</th><th>Avg. position</th></tr></thead><tbody>{(report[tab]||[]).slice(0,100).map((r,i)=><tr key={i}><th scope="row">{r.date||r.keys?.[0]}</th><td>{number(r.impressions)}</td><td>{number(r.clicks)}</td><td>{Number.isFinite(r.position)?r.position.toFixed(1):"—"}</td></tr>)}</tbody></table></div>
      {!(report[tab]||[]).length && <p>The provider returned no rows for this view.</p>}
      {(report[tab]||[]).length>100 && <p>Showing the first 100 rows. Use the provider’s full report for more detail.</p>}
    </>}
  </article>;
}
function AiVisibilityAvailability() {
  return <article className="search-report"><h3>AI mentions and citations</h3>
    <p>Automatic AI-mention reporting is unavailable in Lead Porch. This is not a missing sign-in step. Google and Bing search connections do not provide a complete feed of mentions inside ChatGPT.</p>
    <p>No daily uploads are required. You can view the AI-specific reports directly with their providers. These counts cover the experiences and reporting delays each provider supports; they are separate from website referrals.</p>
    <div className="search-links"><a href="https://search.google.com/search-console" target="_blank" rel="noreferrer">Open Google Search Console ↗</a><a href="https://www.bing.com/webmasters" target="_blank" rel="noreferrer">Open Bing → AI Performance ↗</a></div>
  </article>;
}
export default function SearchVisibilityPanel(){
  const {session}=useAuth();const canManage=(session?.roles||[session?.role]).some(r=>['owner','admin'].includes(r));
  const [status,setStatus]=useState(null),[reports,setReports]=useState(null),[days,setDays]=useState(30),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  const [choices,setChoices]=useState(null),[siteUrl,setSiteUrl]=useState(''),[property,setProperty]=useState(''),[bingSite,setBingSite]=useState('https://elliescoaching.com/'),[apiKey,setApiKey]=useState('');
  useEffect(()=>{let active=true;Promise.all([get('/status'),get(`/reports?days=${days}`)]).then(([s,r])=>{if(active){setStatus(s);setReports(r);setSiteUrl(s.google.settings.siteUrl||'');setProperty(s.google.settings.property||'');}}).catch(()=>{if(active)setError('Search reporting could not be loaded. Try again.');});return()=>{active=false;};},[days,revision]);
  const run=async(fn,success)=>{if(busy)return;setBusy(true);setError('');setMessage('');try{const result=await fn();setMessage(success||result?.data?.data?.message||'Saved.');setRevision(v=>v+1);}catch(e){setError(e.response?.data?.error||'The operation could not be completed.');}finally{setBusy(false);}};
  const oauthResult=new URLSearchParams(window.location.search).get('searchConnection');
  const ga=reports?.ga4;
  return <section id="search-visibility" className="search-visibility" aria-labelledby="search-visibility-title"><header><div><p className="search-eyebrow">Discovery and measurement</p><h2 id="search-visibility-title">Search & AI visibility</h2><p>Search appearances → website clicks → visits → inquiries. Each source has its own coverage and reporting delay.</p></div><label>Search reporting period<select value={days} onChange={e=>{setReports(null);setDays(Number(e.target.value));}}><option value={7}>Last 7 complete days</option><option value={30}>Last 30 complete days</option><option value={90}>Last 90 complete days</option></select></label></header>
    <p className="search-warning">ChatGPT does not provide this dashboard with everyone’s private searches or mentions of your business. A zero in the AI referral panel means no identifiable visits were recorded—not that nobody searched for you.</p>
    {oauthResult==='failed'&&<p role="alert">Google connection was not completed. Check the server OAuth setup and grant both read-only reporting permissions.</p>}
    {oauthResult==='connected'&&<p role="status">Google authorization completed. Choose your reporting properties below.</p>}
    {error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
    <fieldset disabled={busy}><legend>Reporting connections</legend>{!status?<p>Checking connections…</p>:<div className="search-report-grid"><article><h3>Google Search Console & Analytics</h3><p>{status.google.connected?'Connected — read-only reporting':'Not connected — no Google data has been imported.'}</p>{canManage&&<>
      <details><summary>Google connection setup</summary><p>Enable the Google Search Console, Google Analytics Admin and Google Analytics Data APIs in the OAuth project. Add this exact authorized redirect URI to its web client:</p><code>{status.googleRedirectUri || 'Configure PUBLIC_BACKEND_URL or SEARCH_GOOGLE_REDIRECT_URI on the server.'}</code><p>Then connect Google and choose the verified Search Console site and GA4 property. An existing Google login or Gmail connection does not grant these reporting permissions.</p><a href="https://console.cloud.google.com/apis/credentials" target="_blank" rel="noreferrer">Open Google Cloud credentials ↗</a></details>
      <button type="button" disabled={!status.googleConfigured} onClick={()=>run(async()=>{const r=await api.post(base+'/google/start');window.location.assign(r.data.data);},'Opening Google…')}>{status.google.connected?'Reconnect Google':'Connect Google'}</button>
      {!status.googleConfigured&&<p>Server setup required: enable Search Console, Analytics Admin and Analytics Data APIs, then register the reporting OAuth callback. No passwords are needed here.</p>}
      {status.google.connected&&<><button type="button" onClick={()=>run(async()=>{const c=await get('/google/properties');setChoices(c);},'Properties loaded.')}>Load available properties</button><button type="button" onClick={()=>run(()=>api.delete(base+'/connection/google'),'Google disconnected.')}>Disconnect</button>
      {choices&&<form onSubmit={e=>{e.preventDefault();run(()=>api.put(base+'/google/properties',{siteUrl,property}),'Google properties saved.');}}><label>Search Console property<select value={siteUrl} onChange={e=>setSiteUrl(e.target.value)}><option value="">Not selected</option>{choices.sites.map(s=><option key={s}>{s}</option>)}</select></label><label>GA4 property<select value={property} onChange={e=>setProperty(e.target.value)}><option value="">Not selected</option>{choices.properties.map(p=><option key={p.id} value={p.id}>{p.name} ({p.id})</option>)}</select></label>{choices.errors.map((e,i)=><p role="alert" key={i}>{e}</p>)}<button>Save properties</button></form>}</>}
    </>}</article><article><h3>Bing Webmaster Tools</h3><p>{status.bing.connected?`Connected: ${status.bing.settings.siteUrl}`:'Not connected — no Bing data has been imported.'}</p>{canManage&&<><details><summary>{status.bing.connected?'Replace connection':'Connect Bing'}</summary><p>In Bing Webmaster Tools, open Settings → API Access. Enter the API key here; it is encrypted on the server and never returned to the browser.</p><form onSubmit={e=>{e.preventDefault();run(async()=>{await api.post(base+'/bing/connect',{apiKey,siteUrl:bingSite});setApiKey('');},'Bing connected.');}}><label>Verified Bing site URL<input required type="url" value={bingSite} onChange={e=>setBingSite(e.target.value)} /></label><label>Bing API key<input required type="password" autoComplete="off" value={apiKey} onChange={e=>setApiKey(e.target.value)} /></label><button disabled={!status.encryptionConfigured}>Verify and connect</button>{!status.encryptionConfigured&&<p>Server credential encryption must be configured first.</p>}</form></details>{status.bing.connected&&<><button type="button" onClick={()=>run(()=>api.post(base+'/bing/sitemap'))}>Submit sitemap.xml to Bing</button><button type="button" onClick={()=>run(()=>api.delete(base+'/connection/bing'),'Bing disconnected.')}>Disconnect</button></>}</>}</article></div>}</fieldset>
    <div className="search-controls"><p>{reports?`${reports.startDate} – ${reports.endDate} · Reports refresh from providers at most hourly when viewed.`:'Loading provider reports…'}</p><button type="button" onClick={()=>{setError('');setRevision(v=>v+1);}}>Reload reports</button></div>
    <div className="search-report-grid"><SearchCard title="Google search performance" report={reports?.googleSearch}/><SearchCard title="Bing search performance" report={reports?.bingSearch}/></div>
    <article className="search-report"><h3>Google Analytics — website activity</h3>{!ga||!['ready','stale'].includes(ga.state)?<p>{ga?.message||'Loading report…'}</p>:<>{ga.state==='stale'&&<p className="search-warning">Showing saved data. {ga.error}</p>}<small>{ga.property} · Retrieved {new Date(ga.fetchedAt).toLocaleString()}</small><dl className="search-totals">{['Sessions','Active users','Page/screen views','Key events'].map((label,i)=><div key={label}><dt>{label}</dt><dd>{ga.totals.length?number(ga.totals[i]):'No data'}</dd></div>)}</dl><p>{ga.note}</p>{ga.metadata?.subjectToThresholding&&<p>Google applied privacy thresholds to this report.</p>}<div className="search-table"><table><caption>GA4 sources — top 100 by sessions</caption><thead><tr><th>Source / medium</th><th>Sessions</th><th>Active users</th><th>Views</th><th>Key events</th></tr></thead><tbody>{ga.sources.map((r,i)=><tr key={i}><th scope="row">{r.source}</th>{r.values.map((v,j)=><td key={j}>{number(v)}</td>)}</tr>)}</tbody></table></div></>}</article>
    <fieldset disabled={busy}><legend>Provider AI reports</legend><AiVisibilityAvailability/></fieldset>
  </section>;
}
