import { useEffect, useState } from "react";
import { FaFacebookF, FaInstagram, FaLinkedinIn, FaTiktok, FaXTwitter } from "react-icons/fa6";
import DashboardCard from "../components/DashboardCard.jsx";
import { fetchGrowthAnalytics } from "../services/api.js";
import "./Analytics.css";

const label = (value) => String(value || "").replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const currency = (value) => Number(value || 0).toLocaleString("en-US", { style: "currency", currency: "USD" });
const platformIcons = { facebook: FaFacebookF, instagram: FaInstagram, linkedin: FaLinkedinIn, tiktok: FaTiktok, x: FaXTwitter };
function PlatformLabel(value) {
  const key = String(value || "").toLowerCase();
  const Icon = platformIcons[key];
  if (!Icon) return label(value);
  return (
    <span className={`analytics-platform-label analytics-platform-label--${key}`}>
      <span className="analytics-platform-label__icon"><Icon /></span>
      {label(value)}
    </span>
  );
}
function MetricTable({ title, rows, columns, note }) { return <DashboardCard title={title}>{note ? <p className="analytics-table-note">{note}</p> : null}<div className="analytics-table-wrap"><table className="analytics-table"><thead><tr>{columns.map((column) => <th key={column.key}>{column.label}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row, index) => <tr key={row.key || row.source || row.campaign || row.coach || index}>{columns.map((column) => <td key={column.key}>{column.format ? column.format(row[column.key]) : row[column.key]}</td>)}</tr>) : <tr><td colSpan={columns.length}>No supported data yet.</td></tr>}</tbody></table></div></DashboardCard>; }
function FunnelVisual({ rows }) { const max = Math.max(...rows.map((row) => Number(row.value || 0)), 1); return <DashboardCard title="Funnel at a glance" className="analytics-visual-card"><div className="analytics-funnel-visual">{rows.slice(0, 6).map((row) => <div key={row.key}><span>{label(row.key)}</span><div><i style={{ width: `${Math.max(3, Number(row.value || 0) / max * 100)}%` }} /></div><strong>{Number(row.value || 0).toLocaleString()}</strong></div>)}</div></DashboardCard>; }
function SourceVisual({ rows }) { const visible = rows.slice(0, 6), max = Math.max(...visible.map((row) => Number(row.leads || 0)), 1); return <DashboardCard title="Lead-source mix" className="analytics-visual-card"><div className="analytics-source-visual">{visible.length ? visible.map((row) => <div key={row.source}><span>{PlatformLabel(row.source)}</span><div><i style={{ width: `${Math.max(3, Number(row.leads || 0) / max * 100)}%` }} /></div><strong>{row.percentOfLeads}%</strong></div>) : <p>No source attribution yet.</p>}</div></DashboardCard>; }

export default function Analytics() {
  const [data, setData] = useState(null); const [error, setError] = useState("");
  useEffect(() => { let active = true; fetchGrowthAnalytics().then((value) => { if (active) setData(value); }).catch(() => { if (active) setError("Growth analytics could not be loaded."); }); return () => { active = false; }; }, []);
  if (!data) return <div className="page-dashboard analytics-page"><h1 className="page-title">Analytics</h1><p>{error || "Loading canonical Lead Porch analytics…"}</p></div>;
  const won = data.funnel.stages.find((item) => item.key === "closed_won")?.value || 0;
  return <div className="page-dashboard analytics-page"><div className="page-header"><div><p className="page-eyebrow">Growth intelligence</p><h1 className="page-title">Analytics</h1><p className="page-subtitle">Sales, marketing, coaching, revenue, communications, referrals, and social attribution from canonical records.</p></div><span className="analytics-health is-healthy">Canonical data · {new Date(data.generatedAt).toLocaleString()}</span></div>
    <h2>Executive overview</h2><section className="analytics-metrics"><DashboardCard title="Tracked revenue"><strong>{currency(data.revenue.total)}</strong><span>closed won + add-ons</span></DashboardCard><DashboardCard title="Active students"><strong>{data.coaching.activeStudents}</strong><span>active enrollments</span></DashboardCard><DashboardCard title="Closed won"><strong>{won}</strong><span>{currency(data.revenue.closedWon)}</span></DashboardCard><DashboardCard title="Pending commission"><strong>{currency(data.referrals.pendingCommission)}</strong><span>immutable ledger</span></DashboardCard><DashboardCard title="Communication blocks"><strong>{data.communication.blocked}</strong><span>policy-visible jobs</span></DashboardCard></section>
    <section className="analytics-visual-grid"><FunnelVisual rows={data.funnel.stages} /><SourceVisual rows={data.attribution.bySource} /></section>
    <section className="analytics-section-grid"><MetricTable title="Sales funnel" rows={data.funnel.stages} columns={[{key:"key",label:"Stage",format:label},{key:"value",label:"Count"}]} /><MetricTable title="Conversion rates" rows={data.funnel.conversions.map((row)=>({...row,key:`${row.from}-${row.to}`}))} columns={[{key:"from",label:"From",format:label},{key:"to",label:"To",format:label},{key:"rate",label:"Rate",format:(value)=>`${value}%`}]} /></section>
    <MetricTable title="Source attribution" rows={data.attribution.bySource} columns={[{key:"source",label:"Source",format:PlatformLabel},{key:"leads",label:"Leads"},{key:"percentOfLeads",label:"% of leads",format:(value)=>`${value}%`},{key:"applications",label:"Applications"},{key:"sales",label:"Sales"},{key:"revenue",label:"Revenue",format:currency},{key:"conversionRate",label:"Conversion",format:(value)=>`${value}%`}]} />
    <section className="analytics-section-grid"><MetricTable title="Campaign/content revenue" rows={data.attribution.byCampaign} columns={[{key:"campaign",label:"Campaign / content"},{key:"sales",label:"Sales"},{key:"revenue",label:"Revenue",format:currency}]} /><MetricTable title="Leads by post/content" note="CRM lead and revenue attribution per post. For live likes, comments, and shares on a specific post, open that post's card in the Content Library." rows={data.attribution.byContent} columns={[{key:"contentId",label:"Content ID"},{key:"provider",label:"Platform",format:PlatformLabel},{key:"leads",label:"Leads"},{key:"percentOfLeads",label:"% of leads",format:(value)=>`${value}%`},{key:"applications",label:"Applications"},{key:"sales",label:"Sales"},{key:"revenue",label:"Revenue",format:currency},{key:"conversionRate",label:"Conversion",format:(value)=>`${value}%`}]} /><MetricTable title="Coach referral revenue" rows={data.attribution.byCoachReferral} columns={[{key:"coach",label:"Coach"},{key:"revenue",label:"Revenue",format:currency}]} /></section>
    <h2>Revenue</h2><section className="analytics-metrics"><DashboardCard title="Program revenue"><strong>{currency(data.revenue.programRevenue)}</strong></DashboardCard><DashboardCard title="Add-on revenue"><strong>{currency(data.revenue.addonRevenue)}</strong></DashboardCard><DashboardCard title="Referral-generated"><strong>{currency(data.revenue.referralGenerated)}</strong></DashboardCard><DashboardCard title="Commission expense"><strong>{currency(data.revenue.commissionExpense)}</strong></DashboardCard><DashboardCard title="Customer lifetime value"><strong>{currency(data.revenue.customerLifetimeValue)}</strong></DashboardCard></section>
    <section className="analytics-section-grid"><MetricTable title="Students per coach" rows={data.coaching.studentsPerCoach} columns={[{key:"key",label:"Coach"},{key:"value",label:"Students"}]} /><MetricTable title="Program enrollments" rows={data.coaching.programEnrollments} columns={[{key:"key",label:"Program"},{key:"value",label:"Enrollments"}]} /></section>
    <section className="analytics-metrics"><DashboardCard title="Upcoming assignments"><strong>{data.coaching.upcomingAssignments}</strong></DashboardCard><DashboardCard title="Completed assignments"><strong>{data.coaching.completedAssignments}</strong></DashboardCard><DashboardCard title="Handoffs"><strong>{data.coaching.handoffs}</strong></DashboardCard><DashboardCard title="Attended sessions"><strong>{data.coaching.attendance.attended}</strong></DashboardCard><DashboardCard title="No-shows"><strong>{data.coaching.attendance.noShows}</strong></DashboardCard></section>
    <h2>Communications</h2><section className="analytics-metrics"><DashboardCard title="Emails sent"><strong>{data.communication.email.sent}</strong></DashboardCard><DashboardCard title="Email delivered"><strong>{data.communication.email.delivered}</strong></DashboardCard><DashboardCard title="Email opened"><strong>{data.communication.email.opened}</strong></DashboardCard><DashboardCard title="Email clicked"><strong>{data.communication.email.clicked}</strong></DashboardCard><DashboardCard title="Email bounced"><strong>{data.communication.email.bounced}</strong></DashboardCard><DashboardCard title="SMS sent"><strong>{data.communication.sms.sent}</strong></DashboardCard><DashboardCard title="SMS delivered"><strong>{data.communication.sms.delivered}</strong></DashboardCard><DashboardCard title="SMS replies"><strong>{data.communication.sms.replies}</strong></DashboardCard><DashboardCard title="Reminders sent"><strong>{data.communication.reminders.sent}</strong></DashboardCard></section>
    <p className="analytics-disclaimer">Attribution includes only identifiable canonical Contacts and supported events. Anonymous views, likes, saves, and unsupported Skool course progress are excluded.</p>
  </div>;
}
