import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { FiArrowRight, FiBarChart2, FiCalendar, FiCheck, FiChevronRight, FiMessageCircle, FiSearch, FiSend, FiTarget, FiTrendingUp, FiUsers, FiZap } from "react-icons/fi";
import useAuth from "../context/useAuth.js";
import useInitiative from "../context/useInitiative.js";
import { fetchCampaigns, fetchEvents, fetchGrowthAnalytics, fetchIntentSignals, fetchJarvisMorningLeadStatus } from "../services/api.js";
import "./Dashboard.css";

const number = (value) => Number(value || 0).toLocaleString();
const currency = (value) => Number(value || 0).toLocaleString("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });

function JarvisOrb({ active = false }) {
  return <div className={`jarvis-orb ${active ? "jarvis-orb--active" : ""}`} aria-hidden="true"><div className="jarvis-orb__aura" /><div className="jarvis-orb__ring jarvis-orb__ring--outer" /><div className="jarvis-orb__ring jarvis-orb__ring--inner" /><div className="jarvis-orb__core"><span>J</span></div><i className="jarvis-orb__satellite jarvis-orb__satellite--one" /><i className="jarvis-orb__satellite jarvis-orb__satellite--two" /></div>;
}

function SignalCard({ label, value, detail, icon, tone }) {
  return <article className={`signal-card signal-card--${tone}`}><div className="signal-card__top"><span>{label}</span><i>{icon}</i></div><strong>{value}</strong><small>{detail}</small><div className="signal-card__spark" aria-hidden="true">{[34,46,39,58,52,72,66,86].map((height,index)=><i key={index} style={{height:`${height}%`}} />)}</div></article>;
}

export default function Dashboard() {
  const navigate = useNavigate();
  const { session } = useAuth();
  const { selectedId: initiativeId } = useInitiative();
  const [events,setEvents] = useState([]), [campaigns,setCampaigns] = useState([]), [analytics,setAnalytics] = useState(null), [morningLeads,setMorningLeads] = useState(null), [liveLeads,setLiveLeads] = useState(null), [loading,setLoading] = useState(true), [prompt,setPrompt] = useState(""), [promptFocused,setPromptFocused] = useState(false);
  useEffect(()=>{let active=true;Promise.allSettled([fetchEvents(),fetchCampaigns(),fetchGrowthAnalytics(),fetchJarvisMorningLeadStatus(),fetchIntentSignals({bucket:"live_lead",limit:250})]).then(([eventResult,campaignResult,analyticsResult,leadResult,liveLeadResult])=>{if(!active)return;setEvents(eventResult.status==="fulfilled"&&Array.isArray(eventResult.value)?eventResult.value:[]);setCampaigns(campaignResult.status==="fulfilled"&&Array.isArray(campaignResult.value)?campaignResult.value:[]);setAnalytics(analyticsResult.status==="fulfilled"?analyticsResult.value:null);setMorningLeads(leadResult.status==="fulfilled"?leadResult.value:null);setLiveLeads(liveLeadResult.status==="fulfilled"?liveLeadResult.value:null);}).finally(()=>active&&setLoading(false));return()=>{active=false};},[]);
  const stage=(key)=>analytics?.funnel?.stages?.find((item)=>item.key===key)?.value||0;
  const firstName=String(session?.user?.name||"").trim().split(/\s+/)[0]||"there";
  const activeCampaigns=campaigns.filter((item)=>["active","running","scheduled"].includes(item.status)).length;
  const selectedCampaign=initiativeId==="all"?null:campaigns.find((item)=>item._id===initiativeId);
  const liveLeadCount=liveLeads?.summary?.total ?? liveLeads?.signals?.length ?? 0;
  const unreviewedLeadCount=(liveLeads?.signals||[]).filter((item)=>item.status==="new").length;
  const recommendations=useMemo(()=>[{icon:<FiTarget />,tone:"violet",label:"High impact",title:`Review ${number(unreviewedLeadCount)} new lead${unreviewedLeadCount===1?"":"s"}`,detail:`${number(liveLeadCount)} live leads are currently visible in Discovery, with evidence and next actions attached.`,action:"Review live leads",path:"/discovery?tab=leads"},{icon:<FiMessageCircle />,tone:"cyan",label:"Revenue opportunity",title:"Rescue five warm conversations",detail:"These prospects engaged recently and are still waiting for a useful follow-up.",action:"Open conversations",path:"/conversations"}],[liveLeadCount,unreviewedLeadCount]);
  const submitPrompt=(event)=>{event.preventDefault();const value=prompt.trim();navigate(`/operators/jarvis${value?`?prompt=${encodeURIComponent(value)}`:""}`)};
  if(loading)return <div className="command-loading"><JarvisOrb active/><strong>Jarvis is preparing your workspace…</strong></div>;
  return <div className="page-dashboard command-center command-center--ai">
    <header className="command-topbar"><div><span>Owner workspace</span><h1>Good morning, <em>{firstName}</em></h1></div><button type="button" className="command-search" onClick={()=>navigate("/crm/contacts")}><FiSearch/><span>Search Lead Porch</span><kbd>⌘ K</kbd></button></header>
    <section className="jarvis-command" aria-labelledby="jarvis-command-title"><div className="jarvis-command__copy"><p className="jarvis-command__status"><i/> Jarvis is online</p><h2 id="jarvis-command-title">What should we <em>grow</em> today?</h2><p>Jarvis has already analyzed your pipeline, conversations, campaigns, and new lead signals.</p><form className={`jarvis-command__prompt ${promptFocused?"is-focused":""}`} onSubmit={submitPrompt}><FiZap/><input value={prompt} onChange={(event)=>setPrompt(event.target.value)} onFocus={()=>setPromptFocused(true)} onBlur={()=>setPromptFocused(false)} placeholder="Ask Jarvis to find leads, build a campaign, or plan my day…" aria-label="Ask Jarvis"/><button type="submit" aria-label="Send to Jarvis"><FiArrowRight/></button></form><div className="jarvis-command__suggestions">{[["Find new leads",FiUsers],["Build a campaign",FiSend],["Plan my day",FiCalendar],["Summarize pipeline",FiBarChart2]].map(([label,Icon])=><button type="button" key={label} onClick={()=>setPrompt(label)}><Icon/>{label}</button>)}</div><div className="jarvis-prospect-desk" aria-label="Jarvis morning prospect desk"><span>Jarvis morning prospect desk</span><strong>Found today <b>{number(morningLeads?.foundToday)}</b></strong><strong>Waiting for review <b>{number(morningLeads?.pendingReview)}</b></strong></div></div><div className="jarvis-command__visual"><JarvisOrb active/><p>Intelligence across your whole business</p></div></section>
    <section className="jarvis-recommendations"><header><div><span><FiZap/> Jarvis recommends</span><h2>Your highest-leverage moves</h2></div><button type="button" onClick={()=>navigate("/operators/jarvis")}>See all recommendations <FiArrowRight/></button></header><div className="jarvis-recommendations__grid">{recommendations.map((item)=><article className={`jarvis-action jarvis-action--${item.tone}`} key={item.title}><span className="jarvis-action__icon">{item.icon}</span><div><small>{item.label}</small><h3>{item.title}</h3><p>{item.detail}</p></div><button type="button" onClick={()=>navigate(item.path)}>{item.action}<FiChevronRight/></button></article>)}<aside className="jarvis-insight"><span><FiZap/> Jarvis insight</span><p>You’re <strong>2.3× more likely</strong> to close this week if you re-engage qualified leads today.</p><button type="button" onClick={()=>navigate("/opportunities")}>Show me the leads <FiArrowRight/></button></aside></div></section>
    <section className="growth-signals" aria-label="Live growth signals"><SignalCard label="Pipeline" value={currency(analytics?.revenue?.pipeline||analytics?.revenue?.total||0)} detail="Current attributed pipeline" icon={<FiTrendingUp/>} tone="violet"/><SignalCard label="Live leads" value={number(liveLeadCount)} detail={`${number(unreviewedLeadCount)} need a decision`} icon={<FiUsers/>} tone="cyan"/><SignalCard label="Conversations" value={number(analytics?.communication?.conversations||0)} detail="Active recorded conversations" icon={<FiMessageCircle/>} tone="coral"/><SignalCard label="Campaign ROI" value={`${Number(analytics?.attribution?.roi||0).toFixed(1)}×`} detail={`${activeCampaigns} active campaign${activeCampaigns===1?"":"s"}`} icon={<FiZap/>} tone="emerald"/></section>
    <section className="command-bottom-grid"><article className="activity-stream"><header><div><span>Live activity</span><h2>Growth happening now</h2></div><button type="button" onClick={()=>navigate("/analytics")}>View all <FiArrowRight/></button></header><div className="activity-stream__items">{[[FiUsers,"New lead matched",morningLeads?.foundToday?`${morningLeads.foundToday} prospects found today`:"Riverside Property Group · 2m"],[FiMessageCircle,"Conversation updated","Jenna Park replied · 14m"],[FiSend,"Campaign gaining momentum",selectedCampaign?.name||events[0]?.name||"Fall Intensive · 31m"],[FiCheck,"Deal moved forward",`${number(stage("qualified")||7)} qualified opportunities`]].map(([Icon,title,detail])=><div key={title}><i><Icon/></i><span><strong>{title}</strong><small>{detail}</small></span></div>)}</div></article><aside className="jarvis-continuity" onClick={()=>navigate("/operators/jarvis")}><JarvisOrb/><span>Jarvis keeps going</span><h2>More growth ahead.</h2><p>Continue the conversation and turn an insight into action.</p><button type="button">Open Jarvis <FiArrowRight/></button></aside></section>
  </div>;
}
